export enum Role {
  // MASTER ROLE
  Founder = 'Founder',
  // ADMIN ROLES
  Administrator = 'Administrator',
  SystemAdministrator = 'SystemAdministrator',
  ServiceAdministrator = 'ServiceAdministrator',
  // STAFF ROLES
  Support = 'Support',
  SuperModerator = 'SuperModerator',
  Validator = 'Validator',
  // VIP ROLES
  Vip = 'Vip',
  // PARTNER ROLES
  PartnerManager = 'PartnerManager',
  Partner = 'Partner',
  // AFFILIATE ROLES
  AffiliateManager = 'AffiliateManager',
  Affiliate = 'Affiliate',
  // VENDOR ROLES
  VendorManager = 'VendorManager',
  Vendor = 'Vendor',
  // CREATOR ROLES
  CreatorManager = 'CreatorManager',
  Creator = 'Creator',
  Editor = 'Editor',
  // USER ROLES
  Member = 'Member',
}
